
---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "29"
year: "2016"
contributor: 
- "Adrian Pohl"
- "Fabian Steeg"
title: "NWBib – Zurück ins Web"
date: 
abstract: ""
comments: false
sharing: true
footer: true

---